# Generated by Django 3.0.2 on 2020-04-27 08:24

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketNumber', models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='Ticket Numarası')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', ckeditor.fields.RichTextField()),
                ('first_name', models.CharField(max_length=254, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=254, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu Tarih')),
                ('updatedDate', models.DateTimeField(verbose_name='Son Güncelleme')),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktiflik')),
                ('isRead', models.BooleanField(blank=True, default=False, null=True, verbose_name='Okunma')),
                ('resolved', models.BooleanField(blank=True, default=False, null=True, verbose_name='Çözüldü')),
                ('tree', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, null=True, size=None)),
                ('isTicket', models.BooleanField(default=True, verbose_name='Ticket mı?')),
                ('isReply', models.BooleanField(default=True, verbose_name='Yanıt mı?')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.Ticket', verbose_name='Ana Ticket mı?')),
            ],
            options={
                'db_table': 'Ticket',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Yorum Id')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Like')),
                ('creator', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('ticketId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.Ticket', verbose_name='Ticket Id')),
            ],
            options={
                'db_table': 'TicketReply',
                'ordering': ['-createdDate'],
            },
        ),
    ]
